### ISSUE TITLE
Controller signatures should use Models instead of IDs

### ISSUE THREAD

**Issue by etopian** [awais-vteams/laravel-crud-generator#24]
The result of using IDs instead of Model objects on Controller is that some routes are registered like for instance {table_name}/list that should return not found and will if you used Models as signatures with the recommended route.

For instance 
```
    public function show(Server $server)
    {
        return view('server.show', compact('server'));
    }
```

Instead of
```
    public function show($id)
    {
        $server = Server::find($id);

        return view('server.show', compact('server'));
    }
```

You can also add the Request object to the controller
```
    /**
     * Display the specified resource.
     */
    public function show(Request $request, Server $server)
    {
        return view('server.show', compact('server'));
    }
```
These are auto-loaded by Laravel.

**Comment by johnsmith-fcs** [comment]
@etopian Actually for some reason where users add custom routes it will not work because the routes param name should be equal to the name of the variable defined in controller arguments. 

but I have improved within the next version [2.x](https://github.com/awais-vteams/laravel-crud-generator/tree/2.x) Please look into the new version that will be relasing soon with Tailwind, Livewire, React, etc https://github.com/awais-vteams/laravel-crud-generator/tree/2.x

**Comment by awais-vteams** [comment]
@etopian Actually for some reason where users add custom routes it will not work because the routes param name should be equal to the name of the variable defined in controller arguments.

but I have improved within the next version [2.x](https://github.com/awais-vteams/laravel-crud-generator/tree/2.x) Please look into the new version that will be relasing soon with Tailwind, Livewire, React, etc https://github.com/awais-vteams/laravel-crud-generator/tree/2.x

**Comment by awais-vteams** [comment]
I got your point already and you are correct too. It will updated in the next version. Thannks
